# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql_service.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:26 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/06 10:11:36 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: v1
kind: Service
metadata:
  namespace: ft-services
  name: mysql-service
  labels:
    app: mysql

spec:
  type: ClusterIP
  selector:
    app: mysql

  ports:
  - name: mysql
    port: 3306