# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql_pod.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:23 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/16 15:57:24 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Pod
metadata:
    name: mysql-pod
    labels:
      project: ft_services
      app: mysql
spec:
    containers:
    - name: mysql
      ports:
      - containerPort: 3306
        hostPort: 3306
      image: ft_mysql:1.0