apiVersion: v1
kind: Service
metadata:
    project: ft_services
    name: mysql-service
spec:
  selector:
    project: ft_services
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql