# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql_deployment.yaml                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:23 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/06 10:11:31 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: mysql
  labels:
    app: mysql

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql

    spec:
      restartPolicy: Always
      containers:
      - name: mysql
        image: ft_mysql:1.0
        
        ports:
        - name: mysql
          containerPort: 3306
          
        env:
        - name: MYSQL_ROOT_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password