# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql_service.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:26 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/19 09:45:50 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ft_services

spec:
  selector:
    app: ft_services
    tier: mysql
  ports:
  - port: 3306
  clusterIP: None