# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql_volume.yaml                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: felix <felix@student.42lyon.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/13 10:18:40 by felix             #+#    #+#              #
#    Updated: 2021/01/13 10:20:04 by felix            ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ft-services
  name: mysql-volume
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi