# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql_deployment.yaml                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: felix <felix@student.42lyon.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:23 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/13 15:45:08 by felix            ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: mysql
  labels:
    app: mysql

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql

    spec:
      restartPolicy: Always

      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
              claimName: mysql-volume

      containers:
      - name: mysql
        image: ft_mysql:1.0
        
        ports:
        - name: mysql
          containerPort: 3306

        volumeMounts:
          - name: mysql-persistent-volume
            mountPath: /Application/MySQL_DATA
          
        env:
        - name: MYSQL_ROOT_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password