# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql_service.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:26 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/16 15:57:27 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
    project: ft_services
    name: mysql-service
spec:
  selector:
    project: ft_services
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql