# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    grafana_deployment.yaml                            :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/07/20 11:17:39 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/11 15:13:42 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: grafana
  labels:
    app: grafana

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      restartPolicy: Always
      containers:
      - name: grafana
        image: ft_grafana:1.0

        ports:
        - name: grafana
          containerPort: 3000
        env:
          # Database Config
          - name: GF_DATABASE_HOST
            value: mysql-service
          - name: GF_DATABASE_NAME
            value: grafana
          - name: GF_DATABASE_TYPE
            value: mysql
          - name: GF_DATABASE_USER 
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: GF_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password