# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx_volume.yaml                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: felix <felix@student.42lyon.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/13 11:01:11 by felix             #+#    #+#              #
#    Updated: 2021/01/13 13:01:11 by felix            ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ft-services
  name: nginx-volume
  labels:
    app: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi