# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx_service_ssh.yaml                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:15 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/16 15:57:16 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
    name: ssh-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    name: ssh