# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx_service.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:18 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/16 15:57:19 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - port: 80
    name: http
  - port: 443
    name: https