# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx_deployment.yaml                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:11 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/16 10:11:51 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: nginx
  labels:
    app: nginx

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx

    spec:
      restartPolicy: Always

      volumes:
        - name: nginx-persistent-volume
          persistentVolumeClaim:
              claimName: nginx-volume

      containers:
      - name: nginx
        image: ft_nginx:1.0

        ports:
        - name: https
          containerPort: 443
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22

        env:
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: username
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssh-secret
              key: password 

        volumeMounts:
          - name: nginx-persistent-volume
            mountPath: /Application/WWW