# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx_deployment.yaml                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: felix <felix@student.42lyon.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:11 by fgalaup           #+#    #+#              #
#    Updated: 2020/12/24 17:04:29 by felix            ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: nginx
  labels:
    app: nginx

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx

    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: ft_nginx:1.0
        ports:
        - name: https
          containerPort: 443
        - name: http
          containerPort: 80