# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx_pod.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:11 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/16 15:57:12 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod
    labels:
      app: nginx
spec:
    containers:
    - name: nginx
      image: ft_nginx:1.0