# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps_deployment.yaml                               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/20 10:45:24 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/06 16:43:35 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: ftps
  labels:
    app: ftps

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps

    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        image: ft_ftps:1.0

        ports:
        - name: ftps
          containerPort: 21
        - name: ftps-data
          containerPort: 15000
          
        env:
        - name: FTP_USER
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: username
        - name: FTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps-secret
              key: password