# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps_service.yaml                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/20 10:44:46 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/14 17:24:41 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: v1
kind: Service
metadata:
  namespace: ft-services
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool

spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
  - name: ftps-data0
    port: 15000
    targetPort: 15000
  - name: ftps-data1
    port: 15001
    targetPort: 15001
  - name: ftps-data2
    port: 15002
    targetPort: 15002