# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps_deployment.yaml                               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/20 10:45:24 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/20 11:58:26 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ft_services

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ft_services
        tier: ftps
    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        image: ft_ftps:1.0

        ports:
        - containerPort: 21
          name: ftps
        env:
        - name: FTP_USER
          valueFrom:
            secretKeyRef:
              name: ftps-user
              key: username
        - name: FTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps-user
              key: password