# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress_deployment.yaml                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/05 18:50:13 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/09 15:40:03 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: wordpress
  labels:
    app: wordpress

spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress

    spec:
      restartPolicy: Always
      containers:
      - name: wordpress
        image: ft_wordpress:1.0

        ports:
        - name: wordpress
          containerPort: 80

        env:
        # Database Configuration
        - name: WORDPRESS_DATABASE_HOST
          value: "mysql-service"
        - name: WORDPRESS_DATABASE_PORT
          value: "3306"
        - name: WORDPRESS_DATABASE_NAME
          value: "wordpress"
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

        # Admin Configuration
        - name: WORDPRESS_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: email
        - name: WORDPRESS_ADMIN_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: username

        - name: WORDPRESS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password

        # User Import
        - name: WORDPRESS_USER_IMPORT_CSV
          value: "true"

        # Other Config
        - name: WORDPRESS_SITE_URL
          value: http://192.168.99.100:5050