# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    kustomization.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/17 15:38:11 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/20 11:57:45 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Kubernetes environment config
secretGenerator:
  - name: ssh-user
    literals:
    - username=admin
    - password=admin
  - name: mysql-root
    literals:
    - username=root
    - password=root
  - name: ftps-user
    literals:
    - username=admin
    - password=admin

# Other Kubernetes resources
resources:
    - ./Ingress/ingress_redirect.yaml
      # Nginx
    - ./Nginx/nginx_deployment.yaml
    - ./Nginx/nginx_service.yaml
    - ./Nginx/nginx_service_ssh.yaml
      # MySQL
    - ./MySQL/mysql_deployment.yaml
    - ./MySQL/mysql_service.yaml
      # PHPMyAdmin
    - ./PHPMyAdmin/phpmyadmin_deployment.yaml
    - ./PHPMyAdmin/phpmyadmin_service.yaml
      # WordPress
    - ./WordPress/wordpress_deployment.yaml
    - ./WordPress/wordpress_service.yaml
      # FTPS
    - ./FTPS/ftps_deployment.yaml
    - ./FTPS/ftps_service.yaml

  # - kubernetes-dashboard.yaml
  # - ftps.yaml
  # - grafana.yaml
  # - influxdb.yaml
  # - telegraf.yaml