# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    kustomization.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/17 15:38:11 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/10 17:17:29 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Kubernetes resources
resources:
      # Namesapce
    - ./namespace.yaml
      # Load Balancer
    - ./LoadBalancer/metallb_config-map.yaml
      # Nginx
    - ./Nginx/nginx_deployment.yaml
    - ./Nginx/nginx_service.yaml
      # MySQL
    - ./MySQL/mysql_deployment.yaml
    - ./MySQL/mysql_service.yaml
    - ./MySQL/mysql_secrets.yaml
      # PHPMyAdmin
    - ./PHPMyAdmin/phpmyadmin_deployment.yaml
    - ./PHPMyAdmin/phpmyadmin_service.yaml
      # WordPress
    - ./WordPress/wordpress_deployment.yaml
    - ./WordPress/wordpress_service.yaml
    - ./WordPress/wordpress_secrets.yaml
    #   # FTPS
    - ./FTPS/ftps_deployment.yaml
    - ./FTPS/ftps_service.yaml
    - ./FTPS/ftps_secrets.yaml
    #   # InfluxDB
    - ./InfluxDB/influxdb_deployment.yaml
    - ./InfluxDB/influxdb_service.yaml
      # Grafana
    - ./Grafana/grafana_deployment.yaml
    - ./Grafana/grafana_service.yaml
