# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    telegraf_deployment.yaml                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/20 20:52:07 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/15 12:34:53 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: telegraf
  labels:
    app: telegraf

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      restartPolicy: Always

      volumes:
        - name: telegraf-docker
          hostPath:
            path: /var/run/docker.sock

      containers:
      - name: telegraf
        image: ft_telegraf:1.0

        # ports:
        # - name: telegraf
        #   containerPort: 8086

        volumeMounts:
          - name: telegraf-docker
            mountPath: "/var/run/docker.sock"