# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin_service.yaml                            :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: felix <felix@student.42lyon.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:56:57 by fgalaup           #+#    #+#              #
#    Updated: 2020/12/21 14:29:13 by felix            ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: v1
kind: Service
metadata:
  namespace: ft-services
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: address-pool

spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin
    port: 5000
    targetPort: 80