# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin_deployment.yaml                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: felix <felix@student.42lyon.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:04 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/21 16:53:52 by felix            ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: phpmyadmin
  labels:
    app: phpmyadmin

spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        
    spec:
      restartPolicy: Always
      containers:
      - name: phpmyadmin
        image: ft_phpmyadmin:1.0

        ports:
        - name: phpmyadmin
          containerPort: 80

        env:
        - name: PMA_ABSOLUTE_URI
          value: "http://192.168.99.100:5000/"
        - name: PMA_HOST
          value: "mysql-service"
        - name: PMA_PMADB
          value: "phpmyadmin"
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
              
        livenessProbe:
          exec:
            command:
            - sh
            - /HealthCheck.sh
          initialDelaySeconds: 120
          periodSeconds: 5