# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin_pod.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:57:04 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/16 15:57:05 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Pod
metadata:
    name: phpmyadmin-pod
	labels:
	  project: ft_services
      app: phpmyadmin
spec:
    containers:
    - name: phpmyadmin
      image: ft_phpmyadmin:1.0
      ports:
      - containerPort: 80
        hostPort: 5000
      env:
      - name: PMA_HOST
        value: "mysql-pod"
      - name: PMA_PMADB
        value: "phpmyadmin"
      - name: PMA_PORT
        value: "3306"
      - name: PMA_USER
        value: "root"
      - name: PMA_PASSWORD
        value: "root"
