# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin_service.yaml                            :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/16 15:56:57 by fgalaup           #+#    #+#              #
#    Updated: 2020/06/16 15:56:59 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-service
spec:
  selector:
	project: ft_services
    app: phpmyadmin
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    name: phpmyadmin