# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    influxdb_service.yaml                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: felix <felix@student.42lyon.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/20 20:45:35 by fgalaup           #+#    #+#              #
#    Updated: 2020/12/24 15:05:02 by felix            ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: v1
kind: Service
metadata:
  namespace: ft-services
  name: influxdb-service
  labels:
    app: influxdb

spec:
  type: ClusterIP
  selector:
    app: influxdb

  ports:
  - name: influxdb
    port: 8086