# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    influxdb_deployment.yaml                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: felix <felix@student.42lyon.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/20 20:52:07 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/13 12:50:35 by felix            ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: influxdb
  labels:
    app: influxdb

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always

      volumes:
        - name: influxdb-persistent-volume
          persistentVolumeClaim:
              claimName: influxdb-volume

      containers:
      - name: influxdb
        image: ft_influxdb:1.0

        ports:
        - name: influxdb
          containerPort: 8086

        volumeMounts:
          - name: influxdb-persistent-volume
            mountPath: /Application/InfluxDB