# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    influxdb_deployment.yaml                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgalaup <fgalaup@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/06/20 20:52:07 by fgalaup           #+#    #+#              #
#    Updated: 2021/01/10 15:19:46 by fgalaup          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

# Header
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ft-services
  name: influxdb
  labels:
    app: influxdb

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always
      containers:
      - name: influxdb
        image: ft_influxdb:1.0

        ports:
        - name: influxdb
          containerPort: 8086