# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    influxdb_volume.yaml                               :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: felix <felix@student.42lyon.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/13 12:41:40 by felix             #+#    #+#              #
#    Updated: 2021/01/13 12:42:03 by felix            ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ft-services
  name: influxdb-volume
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi